FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Directorio dentro del contenedor
WORKDIR /app

# Java para Spark
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-21-jre \
    curl \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

# Spark
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH="$SPARK_HOME/bin:$PATH"

RUN mkdir -p /opt/spark && \
    curl -L "https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" \
    -o spark.tgz && \
    tar -xzf spark.tgz -C /opt/spark --strip-components=1 && \
    rm spark.tgz

# -------- CORRECCIÓN CRÍTICA -------------
# Copiar TODO el proyecto (contexto actual ES la raíz)
COPY . /app/
# ------------------------------------------

# Instalar dependencias
RUN pip install --no-cache-dir -r /app/dependencies.txt

# Para que Python detecte el paquete app/
ENV PYTHONPATH="/app"

CMD ["python", "-u", "worker/worker_process.py"]
