FROM python:3.12-slim

# =========================
# 🔹 Instalar dependencias del sistema
# =========================
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-21-jre \
    curl \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

# =========================
# 🔹 Variables de Spark
# =========================
ENV SPARK_VERSION=3.5.1
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin

# =========================
# 🔹 Instalar Spark
# =========================
RUN curl -L \
    https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz \
    -o /tmp/spark.tgz \
    && mkdir -p /opt/spark \
    && tar -xzf /tmp/spark.tgz -C /opt/spark --strip-components=1 \
    && rm /tmp/spark.tgz

# =========================
# 🔹 Instalar dependencias Python
# =========================
WORKDIR /app
COPY dependencies.txt .
RUN pip install --no-cache-dir -r dependencies.txt

# Copiar proyecto
COPY . .

EXPOSE 8000

# Iniciar API (prod)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
